### ISSUE TITLE
Formant preservation?

### ISSUE THREAD

**Issue by milasudril** [x42/fat1.lv2#1]
It would be really nice to add formant preservation. That is beneficial also for  small corrections.

**Comment by x42** [comment]
If this happens it'll have to be done upstream at zita-at1. This is basically just a "LV2 shell" around the upstream project and I prefer to not fork the project, but rather add to it.

Then again re-tuning is in zita-at1 is basically just re-sampling and looping, so conceptually it's not feasible with the current approach.

**Comment by milasudril** [comment]
Do you know anything about algorithms that can be used for formant preservation, or any tips on where I can read more? I have thought of implementing something on my own. I need a native version of KeroVee.

**Comment by timofonic** [comment]
@x42 So are there plans to merge it again? I see these tools are interesting in audio,
Despite the freedom and even many technical advantages (optimization, portability, security, independence...). It's common that certain software is less user friendly in FOSS, but it's improving these days.

What I find more annoying:

- Project segmentation: Different tools for the same and code not really agnostic (core stuff depending on GTK, Qt or any other framework that has it's own way).

- Messy GUIs: It's common, because even very good programmers can be awful at designing user interfaces. It's not only about the visual aspect, but  usability.

**Comment by x42** [comment]
@timofonic merge what again? 

If you mean zita-at1, there have not been any upstream changes since 2014: http://kokkinizita.linuxaudio.org/linuxaudio/downloads/index.html and there are no plans as far as I know to change the algorithm or shoehorn some format correction onto the resampler.

I don't understand your rant either.  While it's true that some plugins do use unsuitable kitchen-sink frameworks, x42-plugins do not depend on GTK nor QT nor any framework. 
Just openGL, compatible back to 1.4 (early 2000s) and pango/cairo. If you want ready-to-run binaries: http://x42-plugins.com/x42/x42-autotune

If you don't like the GUI layout or design, complaining does not help, constructive criticism, mockups or suggestions how to improve  visibility, learnability/discoverability control and interaction will go a lot further than just mentioning a the meaningless u\* buzz-word.

**Comment by AS383** [comment]
@milasudril, for auto tune plugin with formant correction see [TalentedHack](https://github.com/jeremysalwen/TalentedHack). Unfortunately it have artifacts.

**Comment by x42** [comment]
Also keep in mind that this auto-tune works with instruments that don't have formants or fixed resonances.
